title = "My New Hugo Site"
baseurl = "syati.github.io/yourblog"
languageCode = "ja-jp"
theme = "hyde"
canonifyurls = true

[params]
  description = "This is yourblog"
  author = "your name"

[taxonomies]
  category = "categories"
  tag = "tags"


